export const environment = {
  production: true,
  uatLibApi: 'https://static-uat.egovdev.ru',
  uatUrl: 'https://pgu-uat-fed.test.gosuslugi.ru/',
  uatServiceApi: 'https://pgu-uat-fednlb.test.gosuslugi.ru',
  devL11LibApi: 'https://dev-l11-sf-portal.pgu2-pub.test.gosuslugi.ru',
  devL11ServiceApi: 'https://dev-l11.pgu2-pub.test.gosuslugi.ru',
  dev01LibApi: 'https://dev01-sf-portal.pgu2-pub.test.gosuslugi.ru',
  dev01ServiceApi: 'https://dev01.pgu2-pub.test.gosuslugi.ru',
  dev02LibApi: 'https://dev02-sf-portal.pgu2-pub.test.gosuslugi.ru',
  dev02ServiceApi: 'https://dev02.pgu2-pub.test.gosuslugi.ru',
  prodLibApi: 'https://gu-st.ru',
  prodServiceApi: 'https://gosuslugi.ru',
  prodLikeLibApi: 'https://prodlike-sf-portal.pgu2-pub.test.gosuslugi.ru',
  prodLikeServiceApi: 'https://prodlike.pgu2-pub.test.gosuslugi.ru',
};
